INSERT INTO ctrlactividades.TIPO_IDENTIFICACION ( C_DESCRIPCION , C_ABREVIATURA ) VALUES ('CEDULA CIUDADANIA','CC');

INSERT INTO ctrlactividades.TIPO_IDENTIFICACION ( C_DESCRIPCION , C_ABREVIATURA ) VALUES ('CEDULA EXTRANJERIA','CE');

INSERT INTO ctrlactividades.TIPO_IDENTIFICACION ( C_DESCRIPCION , C_ABREVIATURA ) VALUES ('PASAPORTE','PAS');


INSERT INTO ctrlactividades.estado_actividades(C_DESCRIPCION) VALUES('PENDIENTE');

INSERT INTO ctrlactividades.estado_actividades(C_DESCRIPCION) VALUES('EN PROCESO');

INSERT INTO ctrlactividades.estado_actividades(C_DESCRIPCION) VALUES('CULMINADA');


INSERT INTO ctrlactividades.personas (I_TIPO_IDENTIFICACION, C_NUM_IDENTIFICACION, C_NOMBRES, C_PRIMER_APELLIDO, C_SEGUNDO_APELLIDO, C_NUM_CEL, C_EMAIL, C_EMPLEADO)
VALUES(1, '1012405517', 'BRAYAN FABIAN', 'SILVA', 'ROMERO', '3046332508', 'brayanf.silvar@gmail.com', 'S');

INSERT INTO ctrlactividades.personas (I_TIPO_IDENTIFICACION, C_NUM_IDENTIFICACION, C_NOMBRES, C_PRIMER_APELLIDO, C_SEGUNDO_APELLIDO, C_NUM_CEL, C_EMAIL, C_EMPLEADO)
VALUES(1, '1012446385', 'LAURA', 'SANCHEZ', 'CARDENAS', '3007635325', 'laucardenas27@outlook.com', 'S');

INSERT INTO ctrlactividades.personas (I_TIPO_IDENTIFICACION, C_NUM_IDENTIFICACION, C_NOMBRES, C_PRIMER_APELLIDO, C_SEGUNDO_APELLIDO, C_NUM_CEL, C_EMAIL, C_EMPLEADO)
VALUES(1, '12345678', 'CESAR', 'GARCIA', 'GALEANO', '3122460034', 'cesargg06@outlook.com', 'N');