CREATE DATABASE `ctrlactividades` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE USER 'ADM_CTRLACTIVIDADES'@'%' IDENTIFIED BY 'CtrlAct2022*';
GRANT Alter ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Create ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Create view ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Delete ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Delete history ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Drop ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Grant option ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Index ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Insert ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT References ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Select ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Show view ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Trigger ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Update ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Alter routine ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Create routine ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Create temporary tables ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Execute ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Lock tables ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';
GRANT Grant option ON CTRLACTIVIDADES.* TO 'ADM_CTRLACTIVIDADES'@'%';


